package entities;
// Generated Aug 15, 2017 10:17:03 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Book", catalog = "ReviewStrust")
public class Book implements java.io.Serializable {

	private String bookId;
	private String bookTitle;
	private Integer bookPrice;

	public Book() {
	}

	public Book(String bookId) {
		this.bookId = bookId;
	}

	public Book(String bookId, String bookTitle, Integer bookPrice) {
		this.bookId = bookId;
		this.bookTitle = bookTitle;
		this.bookPrice = bookPrice;
	}

	@Id

	@Column(name = "BookID", unique = true, nullable = false, length = 50)
	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	@Column(name = "BookTitle", length = 50)
	public String getBookTitle() {
		return this.bookTitle;
	}

	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	@Column(name = "BookPrice")
	public Integer getBookPrice() {
		return this.bookPrice;
	}

	public void setBookPrice(Integer bookPrice) {
		this.bookPrice = bookPrice;
	}

}
