package entities;
// Generated Aug 3, 2017 10:05:26 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersDetail generated by hbm2java
 */
@Entity
@Table(name = "OrdersDetail", catalog = "mydemo")
public class OrdersDetail implements java.io.Serializable {

	private OrdersDetailId id;
	private Orders orders;
	private Product product;
	private BigDecimal price;
	private Integer quantity;

	public OrdersDetail() {
	}

	public OrdersDetail(OrdersDetailId id, Orders orders, Product product) {
		this.id = id;
		this.orders = orders;
		this.product = product;
	}

	public OrdersDetail(OrdersDetailId id, Orders orders, Product product, BigDecimal price, Integer quantity) {
		this.id = id;
		this.orders = orders;
		this.product = product;
		this.price = price;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ordersId", column = @Column(name = "ordersId", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false)) })
	public OrdersDetailId getId() {
		return this.id;
	}

	public void setId(OrdersDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordersId", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
